mongodb:
  username: admin
  password: password
  hosts: localhost:27017
  database: product
  authSource: admin
  replicaSet: rs0

spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.username}:${mongodb.password}@${mongodb.hosts}/${mongodb.database}?authSource=${mongodb.authSource}&replicaSet=${mongodb.replicaSet}
